import { countryType } from "../types/types";

export const countries: countryType[] = [
  {
    country: "afghanistan",
    capital: "kabul",
    currency: "afghani",
    native_language: ["dari persian", "pashto"],
    famous_for: "rugs, taliban",
    phone_code: "+93",
    flag: "https://flagpedia.net/data/flags/h80/af.png",
    drive_direction: "right",
    alcohol_prohibition: "nationwide",
    area: {
      km2: 652864,
      mi2: 252072,
    },
    continent: "as",
    iso: {
      numeric: "004",
      alpha_2: "af",
      alpha_3: "afg",
    },
    tld: ".af",
    constitutional_form: "republic",
    language_codes: ["fa-AF", "ps-AF"],
    is_landlocked: true,
  },
  {
    country: "albania",
    capital: "tirane",
    currency: "lek",
    native_language: ["albanian"],
    famous_for: "mother teresa",
    phone_code: "+355",
    flag: "https://flagpedia.net/data/flags/h80/al.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 28748,
      mi2: 11100,
    },
    continent: "eu",
    iso: {
      numeric: "008",
      alpha_2: "al",
      alpha_3: "alb",
    },
    tld: ".al",
    constitutional_form: "republic",
    language_codes: ["sq-AL"],
    is_landlocked: false,
  },
  {
    country: "argentina",
    capital: "buenos aires",
    currency: "argentine peso",
    native_language: ["spanish"],
    famous_for: "football",
    phone_code: "+54",
    flag: "https://flagpedia.net/data/flags/h80/ar.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 2780400,
      mi2: 1073500,
    },
    continent: "sa",
    iso: {
      numeric: "032",
      alpha_2: "ar",
      alpha_3: "arg",
    },
    tld: ".ar",
    constitutional_form: "republic",
    language_codes: ["es-AR"],
    is_landlocked: false,
  },
  {
    country: "armenia",
    capital: "yerevan",
    currency: "dram",
    native_language: ["armenian"],
    famous_for: "genocide and kim kardashian",
    phone_code: "+374",
    flag: "https://flagpedia.net/data/flags/h80/am.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 29743,
      mi2: 11484,
    },
    continent: "af",
    iso: {
      numeric: "051",
      alpha_2: "am",
      alpha_3: "arm",
    },
    tld: ".am",
    constitutional_form: "republic",
    language_codes: ["as-AM"],
    is_landlocked: true,
  },
  {
    country: "australia",
    capital: "canberra",
    currency: "australian dollar",
    native_language: ["english"],
    famous_for: "koalas and kangaroos",
    phone_code: "+61",
    flag: "https://flagpedia.net/data/flags/h80/au.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 7692024,
      mi2: 2969907,
    },
    continent: "oc",
    iso: {
      numeric: "036",
      alpha_2: "au",
      alpha_3: "aus",
    },
    tld: ".au",
    constitutional_form: "constitutional monarchy",
    language_codes: ["en-AU"],
    is_landlocked: false,
  },
  {
    country: "austria",
    capital: "vienna",
    currency: "euro",
    native_language: ["german"],
    famous_for:
      "hitler, mozart, redbull, franz ferdinand and arnold schwarzenegger",
    phone_code: "+43",
    flag: "https://flagpedia.net/data/flags/h80/at.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 83871,
      mi2: 32383,
    },
    continent: "eu",
    iso: {
      numeric: "040",
      alpha_2: "at",
      alpha_3: "aut",
    },
    tld: ".at",
    constitutional_form: "republic",
    language_codes: ["de-AT"],
    is_landlocked: true,
  },
  {
    country: "azerbaijan",
    capital: "baku",
    currency: "manat",
    native_language: ["azerbaijani"],
    famous_for: "burning mountain",
    phone_code: "+994",
    flag: "https://flagpedia.net/data/flags/h80/az.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 86600,
      mi2: 33400,
    },
    continent: "as",
    iso: {
      numeric: "031",
      alpha_2: "az",
      alpha_3: "aze",
    },
    tld: ".az",
    constitutional_form: "republic",
    language_codes: ["az-AZ"],
    is_landlocked: true,
  },
  {
    country: "bahrain",
    capital: "manama",
    currency: "bahraini dinar",
    native_language: ["arabic"],
    famous_for: "oil, pearls and world heritage sites",
    phone_code: "+973",
    flag: "https://flagpedia.net/data/flags/h80/bh.png",
    drive_direction: "right",
    alcohol_prohibition: "limited",
    area: {
      km2: 778,
      mi2: 300,
    },
    continent: "as",
    iso: {
      numeric: "048",
      alpha_2: "bh",
      alpha_3: "bhr",
    },
    tld: ".bh",
    constitutional_form: "constitutional monarchy",
    language_codes: ["ar-BH"],
    is_landlocked: false,
  },
  {
    country: "bangladesh",
    capital: "dhaka",
    currency: "taka",
    native_language: ["bangla"],
    famous_for: "cox's bazar sea",
    phone_code: "+880",
    flag: "https://flagpedia.net/data/flags/h80/bd.png",
    drive_direction: "left",
    alcohol_prohibition: "limited",
    area: {
      km2: 147570,
      mi2: 56980,
    },
    continent: "as",
    iso: {
      numeric: "050",
      alpha_2: "bd",
      alpha_3: "bgd",
    },
    tld: ".bd",
    constitutional_form: "republic",
    language_codes: ["bn-BD"],
    is_landlocked: false,
  },
  {
    country: "belarus",
    capital: "minsk",
    currency: "belarusian ruble",
    native_language: ["belarusian", "russian"],
    famous_for: "variety of sweets",
    phone_code: "+375",
    flag: "https://flagpedia.net/data/flags/h80/by.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 207600,
      mi2: 80200,
    },
    continent: "eu",
    iso: {
      numeric: "112",
      alpha_2: "by",
      alpha_3: "blr",
    },
    tld: ".by",
    constitutional_form: "republic",
    language_codes: ["be-BY", "ru-BY"],
    is_landlocked: true,
  },
  {
    country: "belgium",
    capital: "brussels",
    currency: "euro",
    native_language: ["dutch", "french", "german"],
    famous_for: "chocolates, waffles, fries and beer",
    phone_code: "+32",
    flag: "https://flagpedia.net/data/flags/h80/be.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 30528,
      mi2: 11787,
    },
    continent: "eu",
    iso: {
      numeric: "056",
      alpha_2: "be",
      alpha_3: "bel",
    },
    tld: ".be",
    constitutional_form: "constitutional monarchy",
    language_codes: ["de-BE", "fr-BE", "nl-BE"],
    is_landlocked: false,
  },
  {
    country: "bolivia",
    capital: "la paz, sucre",
    currency: "boliviano",
    native_language: ["spanish", "quechua", "aymara"],
    famous_for: "salar de uyuni",
    phone_code: "+591",
    flag: "https://flagpedia.net/data/flags/h80/bo.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 1098581,
      mi2: 424164,
    },
    continent: "sa",
    iso: {
      numeric: "068",
      alpha_2: "bo",
      alpha_3: "bol",
    },
    tld: ".bo",
    constitutional_form: "republic",
    language_codes: ["ay-BO", "es-BO", "qu-BO"],
    is_landlocked: true,
  },
  {
    country: "bosnia and herzegovina",
    capital: "sarajevo",
    currency: "convertible mark",
    native_language: ["bosnian", "croatian", "serbian"],
    famous_for: "natural environment and cultural heritage",
    phone_code: "+387",
    flag: "https://flagpedia.net/data/flags/h80/ba.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 51209,
      mi2: 19772,
    },
    continent: "eu",
    iso: {
      numeric: "070",
      alpha_2: "ba",
      alpha_3: "bih",
    },
    tld: ".ba",
    constitutional_form: "republic",
    language_codes: ["bs-BA", "hr-BA", "sr-BA"],
    is_landlocked: false,
  },
  {
    country: "brazil",
    capital: "brasilia",
    currency: "real",
    native_language: ["portuguese"],
    famous_for: "soccer and football",
    phone_code: "+55",
    flag: "https://flagpedia.net/data/flags/h80/br.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 8515767,
      mi2: 3287956,
    },
    continent: "sa",
    iso: {
      numeric: "076",
      alpha_2: "br",
      alpha_3: "bra",
    },
    tld: ".br",
    constitutional_form: "republic",
    language_codes: ["pt-BR"],
    is_landlocked: false,
  },
  {
    country: "bulgaria",
    capital: "sofia",
    currency: "lev",
    native_language: ["bulgarian"],
    famous_for: "lavender oil and the rose valley",
    phone_code: "+359",
    flag: "https://flagpedia.net/data/flags/h80/bg.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 111002,
      mi2: 42858,
    },
    continent: "eu",
    iso: {
      numeric: "100",
      alpha_2: "bg",
      alpha_3: "bgr",
    },
    tld: ".bg",
    constitutional_form: "republic",
    language_codes: ["bg-BG"],
    is_landlocked: false,
  },
  {
    country: "cambodia",
    capital: "phnom penh",
    currency: "riel",
    native_language: ["khmer"],
    famous_for: "angkor wat hindu temple",
    phone_code: "+855",
    flag: "https://flagpedia.net/data/flags/h80/kh.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 181035,
      mi2: 69898,
    },
    continent: "as",
    iso: {
      numeric: "116",
      alpha_2: "kh",
      alpha_3: "khm",
    },
    tld: ".kh",
    constitutional_form: "constitutional monarchy",
    language_codes: ["km-KH"],
    is_landlocked: false,
  },
  {
    country: "cameroon",
    capital: "yaounde",
    currency: "central african cfa franc",
    native_language: ["french", "english"],
    famous_for: "coffee, cocoa, cotton and oilseeds",
    phone_code: "+237",
    flag: "https://flagpedia.net/data/flags/h80/cm.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 475442,
      mi2: 183569,
    },
    continent: "af",
    iso: {
      numeric: "120",
      alpha_2: "cm",
      alpha_3: "cmr",
    },
    tld: ".cm",
    constitutional_form: "republic",
    language_codes: ["en-CM", "fr-CM"],
    is_landlocked: false,
  },
  {
    country: "canada",
    capital: "ottawa",
    currency: "canadian dollar",
    native_language: ["english", "french"],
    famous_for: "maple syrup, maple trees, politeness and hockey",
    phone_code: "+1",
    flag: "https://flagpedia.net/data/flags/h80/ca.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 9984670,
      mi2: 3855100,
    },
    continent: "na",
    iso: {
      numeric: "124",
      alpha_2: "ca",
      alpha_3: "can",
    },
    tld: ".ca",
    constitutional_form: "constitutional monarchy",
    language_codes: ["en-CA", "fr-CA"],
    is_landlocked: false,
  },
  {
    country: "chile",
    capital: "santiago",
    currency: "chilean peso",
    native_language: ["spanish"],
    famous_for: "country of poets",
    phone_code: "+56",
    flag: "https://flagpedia.net/data/flags/h80/cl.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 756102,
      mi2: 291933,
    },
    continent: "sa",
    iso: {
      numeric: "152",
      alpha_2: "cl",
      alpha_3: "chl",
    },
    tld: ".cl",
    constitutional_form: "republic",
    language_codes: ["es-CL"],
    is_landlocked: false,
  },
  {
    country: "china",
    capital: "beijing",
    currency: "chinese yuan",
    native_language: ["mandarin"],
    famous_for: "kung fu, spitting habit, panda, cheap electronics",
    phone_code: "+86",
    flag: "https://flagpedia.net/data/flags/h80/cn.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 9596961,
      mi2: 3705407,
    },
    continent: "as",
    iso: {
      numeric: "156",
      alpha_2: "cn",
      alpha_3: "chn",
    },
    tld: ".cn",
    constitutional_form: "republic",
    language_codes: ["zh-CN"],
    is_landlocked: false,
  },
  {
    country: "colombia",
    capital: "bogota",
    currency: "colombian peso",
    native_language: ["spanish"],
    famous_for: "mines of muzo, chivor and coscuez",
    phone_code: "+57",
    flag: "https://flagpedia.net/data/flags/h80/co.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 1141748,
      mi2: 440831,
    },
    continent: "sa",
    iso: {
      numeric: "170",
      alpha_2: "co",
      alpha_3: "col",
    },
    tld: ".co",
    constitutional_form: "republic",
    language_codes: ["es-CO"],
    is_landlocked: false,
  },
  {
    country: "costa rica",
    capital: "san jose",
    currency: "colon",
    native_language: ["spanish"],
    famous_for: "coffee beans",
    phone_code: "+506",
    flag: "https://flagpedia.net/data/flags/h80/cr.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 51100,
      mi2: 19700,
    },
    continent: "na",
    iso: {
      numeric: "188",
      alpha_2: "cr",
      alpha_3: "cri",
    },
    tld: ".cr",
    constitutional_form: "republic",
    language_codes: ["es-CR"],
    is_landlocked: false,
  },
  {
    country: "cote d'ivoire (ivory coast)",
    capital: "yamoussoukro, abidjan",
    currency: "west african cfa franc",
    native_language: ["french"],
    famous_for: "religious and ethnic harmony",
    phone_code: "+225",
    flag: "https://flagpedia.net/data/flags/h80/ci.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 322463,
      mi2: 124504,
    },
    continent: "af",
    iso: {
      numeric: "384",
      alpha_2: "ci",
      alpha_3: "civ",
    },
    tld: ".ci",
    constitutional_form: "republic",
    language_codes: ["fr-CI"],
    is_landlocked: false,
  },
  {
    country: "croatia",
    capital: "zagreb",
    currency: "euro",
    native_language: ["croatian"],
    famous_for:
      "game of thrones, stunning natural beauty and 6000km long coast",
    phone_code: "+385",
    flag: "https://flagpedia.net/data/flags/h80/hr.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 56594,
      mi2: 21851,
    },
    continent: "eu",
    iso: {
      numeric: "191",
      alpha_2: "hr",
      alpha_3: "hrv",
    },
    tld: ".hr",
    constitutional_form: "republic",
    language_codes: ["hr-HR"],
    is_landlocked: false,
  },
  {
    country: "cuba",
    capital: "havana",
    currency: "cuban peso",
    native_language: ["spanish"],
    famous_for: "beaches, rum, cigars, fascinating architecture",
    phone_code: "+53",
    flag: "https://flagpedia.net/data/flags/h80/cu.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 109884,
      mi2: 42426,
    },
    continent: "na",
    iso: {
      numeric: "192",
      alpha_2: "cu",
      alpha_3: "cub",
    },
    tld: ".cu",
    constitutional_form: "republic",
    language_codes: ["es-CU"],
    is_landlocked: false,
  },
  {
    country: "cyprus",
    capital: "nicosia",
    currency: "euro",
    native_language: ["greek", "turkish"],
    famous_for: "incredible scenery and history",
    phone_code: "+357",
    flag: "https://flagpedia.net/data/flags/h80/cy.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 9251,
      mi2: 3572,
    },
    continent: "eu",
    iso: {
      numeric: "196",
      alpha_2: "cy",
      alpha_3: "cyp",
    },
    tld: ".cy",
    constitutional_form: "republic",
    language_codes: ["el-CY", "tr-CY"],
    is_landlocked: false,
  },
  {
    country: "czechia",
    capital: "prague",
    currency: "czech koruna",
    native_language: ["czech", "slovak"],
    famous_for: "museums, puppetry, marionette exhibitions and folk festivals",
    phone_code: "+420",
    flag: "https://flagpedia.net/data/flags/h80/cz.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 78865,
      mi2: 30450,
    },
    continent: "eu",
    iso: {
      numeric: "203",
      alpha_2: "cz",
      alpha_3: "cze",
    },
    tld: ".cz",
    constitutional_form: "republic",
    language_codes: ["cs-CZ"],
    is_landlocked: true,
  },
  {
    country: "denmark",
    capital: "copenhagen",
    currency: "danish krone",
    native_language: ["danish"],
    famous_for: "pig meat, healthcare, pastries and cuisine",
    phone_code: "+45",
    flag: "https://flagpedia.net/data/flags/h80/dk.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 43094,
      mi2: 16639,
    },
    continent: "eu",
    iso: {
      numeric: "208",
      alpha_2: "dk",
      alpha_3: "dnk",
    },
    tld: ".dk",
    constitutional_form: "constitutional monarchy",
    language_codes: ["da-DK"],
    is_landlocked: false,
  },

  {
    country: "dominican republic",
    capital: "santo domingo",
    currency: "dominican peso",
    native_language: ["spanish"],
    famous_for: "blue ocean water, white-sand beaches and beautiful resorts",
    phone_code: "+1-809, +1-829, +1-849",
    flag: "https://flagpedia.net/data/flags/h80/do.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 48671,
      mi2: 18792,
    },
    continent: "na",
    iso: {
      numeric: "214",
      alpha_2: "do",
      alpha_3: "dom",
    },
    tld: ".do",
    constitutional_form: "republic",
    language_codes: ["es-DO"],
    is_landlocked: false,
  },

  {
    country: "ecuador",
    capital: "quito",
    currency: "united states dollar",
    native_language: ["spanish"],
    famous_for: "home to galapagos islands",
    phone_code: "+593",
    flag: "https://flagpedia.net/data/flags/h80/ec.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 276841,
      mi2: 106889,
    },
    continent: "sa",
    iso: {
      numeric: "218",
      alpha_2: "ec",
      alpha_3: "ecu",
    },
    tld: ".ec",
    constitutional_form: "republic",
    language_codes: ["es-EC"],
    is_landlocked: false,
  },
  {
    country: "egypt",
    capital: "cairo",
    currency: "egyptian pound",
    native_language: ["arabic"],
    famous_for: "pyramids, sphinx, ai aqsa university and mummies",
    phone_code: "+20",
    flag: "https://flagpedia.net/data/flags/h80/eg.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 1002450,
      mi2: 387050,
    },
    continent: "af",
    iso: {
      numeric: "818",
      alpha_2: "eg",
      alpha_3: "egy",
    },
    tld: ".eg",
    constitutional_form: "republic",
    language_codes: ["ar-EG"],
    is_landlocked: false,
  },

  {
    country: "estonia",
    capital: "tallinn",
    currency: "estonian kroon, euro",
    native_language: ["estonian"],
    famous_for: "medieval architecture",
    phone_code: "+372",
    flag: "https://flagpedia.net/data/flags/h80/ee.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 45227,
      mi2: 17462,
    },
    continent: "eu",
    iso: {
      numeric: "233",
      alpha_2: "ee",
      alpha_3: "est",
    },
    tld: ".ee",
    constitutional_form: "republic",
    language_codes: ["et-EE"],
    is_landlocked: false,
  },
  {
    country: "ethiopia",
    capital: "addis ababa",
    currency: "birr",
    native_language: ["amharic"],
    famous_for: "cradle of mankind",
    phone_code: "+251",
    flag: "https://flagpedia.net/data/flags/h80/et.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 1104300,
      mi2: 426400,
    },
    continent: "af",
    iso: {
      numeric: "231",
      alpha_2: "et",
      alpha_3: "eth",
    },
    tld: ".et",
    constitutional_form: "republic",
    language_codes: ["am-ET"],
    is_landlocked: true,
  },

  {
    country: "finland",
    capital: "helsinki",
    currency: "euro",
    native_language: ["finnish", "swedish"],
    famous_for: "glassware, littala",
    phone_code: "+358",
    flag: "https://flagpedia.net/data/flags/h80/fi.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 338424,
      mi2: 130666,
    },
    continent: "eu",
    iso: {
      numeric: "246",
      alpha_2: "fi",
      alpha_3: "fin",
    },
    tld: ".fi",
    constitutional_form: "republic",
    language_codes: ["fi-FI", "sv-FI"],
    is_landlocked: false,
  },
  {
    country: "france",
    capital: "paris",
    currency: "euro, cfp franc",
    native_language: ["french"],
    famous_for: "eiffel tower, croissant, fashion, smoking and wine",
    phone_code: "+33",
    flag: "https://flagpedia.net/data/flags/h80/fr.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 640679,
      mi2: 247368,
    },
    continent: "eu",
    iso: {
      numeric: "250",
      alpha_2: "fr",
      alpha_3: "fra",
    },
    tld: ".fr",
    constitutional_form: "republic",
    language_codes: ["fr-FR"],
    is_landlocked: false,
  },

  {
    country: "georgia",
    capital: "tbilisi",
    currency: "lari",
    native_language: ["georgian"],
    famous_for: "joseph stalin",
    phone_code: "+995",
    flag: "https://flagpedia.net/data/flags/h80/ge.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 69700,
      mi2: 26900,
    },
    continent: "as",
    iso: {
      numeric: "268",
      alpha_2: "ge",
      alpha_3: "geo",
    },
    tld: ".ge",
    constitutional_form: "republic",
    language_codes: ["ka-GE"],
    is_landlocked: false,
  },
  {
    country: "germany",
    capital: "berlin",
    currency: "euro",
    native_language: ["german"],
    famous_for: "beer, sausage, nazi and cars",
    phone_code: "+49",
    flag: "https://flagpedia.net/data/flags/h80/de.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 357114,
      mi2: 137882,
    },
    continent: "eu",
    iso: {
      numeric: "276",
      alpha_2: "de",
      alpha_3: "deu",
    },
    tld: ".de",
    constitutional_form: "republic",
    language_codes: ["de-DE"],
    is_landlocked: false,
  },
  {
    country: "ghana",
    capital: "accra",
    currency: "ghanaian cedi",
    native_language: ["english"],
    famous_for: "lush forests, diverse animal life, cocoa and gold",
    phone_code: "+223",
    flag: "https://flagpedia.net/data/flags/h80/gh.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 238533,
      mi2: 92098,
    },
    continent: "af",
    iso: {
      numeric: "288",
      alpha_2: "gh",
      alpha_3: "gha",
    },
    tld: ".gh",
    constitutional_form: "republic",
    language_codes: ["en-GH"],
    is_landlocked: false,
  },
  {
    country: "greece",
    capital: "athens",
    currency: "euro",
    native_language: ["greek"],
    famous_for:
      "ancient philosophers, ancient greek gods, sparta and orthodox christianity",
    phone_code: "+30",
    flag: "https://flagpedia.net/data/flags/h80/gr.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 131957,
      mi2: 50949,
    },
    continent: "eu",
    iso: {
      numeric: "300",
      alpha_2: "gr",
      alpha_3: "grc",
    },
    tld: ".gr",
    constitutional_form: "republic",
    language_codes: ["el-GR"],
    is_landlocked: false,
  },

  {
    country: "guatemala",
    capital: "guatemala city",
    currency: "quetzal",
    native_language: ["spanish"],
    famous_for: "volcanic landscape and fascinating mayan culture",
    phone_code: "+502",
    flag: "https://flagpedia.net/data/flags/h80/gt.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 108889,
      mi2: 42042,
    },
    continent: "na",
    iso: {
      numeric: "320",
      alpha_2: "gt",
      alpha_3: "gtm",
    },
    tld: ".gt",
    constitutional_form: "republic",
    language_codes: ["es-GT"],
    is_landlocked: false,
  },

  {
    country: "haiti",
    capital: "port-au-prince",
    currency: "gourde",
    native_language: ["haitian creole", "french"],
    famous_for: "breathtaking beaches and crystal blue waters",
    phone_code: "+509",
    flag: "https://flagpedia.net/data/flags/h80/ht.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 27750,
      mi2: 10710,
    },
    continent: "na",
    iso: {
      numeric: "332",
      alpha_2: "ht",
      alpha_3: "hti",
    },
    tld: ".ht",
    constitutional_form: "republic",
    language_codes: ["fr-HT", "ht-HT"],
    is_landlocked: false,
  },
  {
    country: "honduras",
    capital: "tegucigalpa",
    currency: "lempira",
    native_language: ["spanish"],
    famous_for:
      "rich natural resources, tropical fruit, sugarcane, coffee and growing textiles industry",
    phone_code: "+504",
    flag: "https://flagpedia.net/data/flags/h80/hn.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 112492,
      mi2: 43433,
    },
    continent: "na",
    iso: {
      numeric: "340",
      alpha_2: "hn",
      alpha_3: "hnd",
    },
    tld: ".hn",
    constitutional_form: "republic",
    language_codes: ["es-HN"],
    is_landlocked: false,
  },
  {
    country: "hungary",
    capital: "budapest",
    currency: "forint",
    native_language: ["hungarian"],
    famous_for: "rich natural resources and textiles",
    phone_code: "+36",
    flag: "https://flagpedia.net/data/flags/h80/hu.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 93028,
      mi2: 35918,
    },
    continent: "eu",
    iso: {
      numeric: "348",
      alpha_2: "hu",
      alpha_3: "hun",
    },
    tld: ".hu",
    constitutional_form: "republic",
    language_codes: ["hu-HU"],
    is_landlocked: true,
  },
  {
    country: "iceland",
    capital: "reykjavik",
    currency: "icelandic krona",
    native_language: ["icelandic"],
    famous_for: "largest glaciers in europe",
    phone_code: "+354",
    flag: "https://flagpedia.net/data/flags/h80/is.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 103000,
      mi2: 40000,
    },
    continent: "eu",
    iso: {
      numeric: "352",
      alpha_2: "is",
      alpha_3: "isl",
    },
    tld: ".is",
    constitutional_form: "republic",
    language_codes: ["is-IS"],
    is_landlocked: false,
  },
  {
    country: "india",
    capital: "new delhi",
    currency: "indian rupee",
    native_language: ["hindi", "english"],
    famous_for: "bollywood, yoga, hinduism, food and diversity",
    phone_code: "+91",
    flag: "https://flagpedia.net/data/flags/h80/in.png",
    drive_direction: "left",
    alcohol_prohibition: "regional",
    area: {
      km2: 3287263,
      mi2: 1269219,
    },
    continent: "as",
    iso: {
      numeric: "356",
      alpha_2: "in",
      alpha_3: "ind",
    },
    tld: ".in",
    constitutional_form: "republic",
    language_codes: ["en-IN", "hi-IN"],
    is_landlocked: false,
  },
  {
    country: "indonesia",
    capital: "jakarta",
    currency: "rupiah",
    native_language: ["indonesian"],
    famous_for: "bali, komodo dragon, domestic workers and rendang",
    phone_code: "+62",
    flag: "https://flagpedia.net/data/flags/h80/id.png",
    drive_direction: "left",
    alcohol_prohibition: "regional",
    area: {
      km2: 1910931,
      mi2: 737815,
    },
    continent: "as",
    iso: {
      numeric: "360",
      alpha_2: "id",
      alpha_3: "idn",
    },
    tld: ".id",
    constitutional_form: "republic",
    language_codes: ["id-ID"],
    is_landlocked: false,
  },
  {
    country: "iraq",
    capital: "baghdad",
    currency: "iraqi dinar",
    native_language: ["arabic", "kurdish"],
    famous_for: "saddam hussein, isis",
    phone_code: "+964",
    flag: "https://flagpedia.net/data/flags/h80/iq.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 438317,
      mi2: 169235,
    },
    continent: "as",
    iso: {
      numeric: "368",
      alpha_2: "iq",
      alpha_3: "irq",
    },
    tld: ".iq",
    constitutional_form: "republic",
    language_codes: ["ar-IK", "ku-IK"],
    is_landlocked: false,
  },
  {
    country: "republic of ireland",
    capital: "dublin",
    currency: "euro",
    native_language: ["english", "irish"],
    famous_for: "meadows and leprechaun",
    phone_code: "+353",
    flag: "https://flagpedia.net/data/flags/h80/ie.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 70273,
      mi2: 27133,
    },
    continent: "eu",
    iso: {
      numeric: "372",
      alpha_2: "ie",
      alpha_3: "irl",
    },
    tld: ".ie",
    constitutional_form: "republic",
    language_codes: ["en-IE", "ga-IE"],
    is_landlocked: false,
  },
  {
    country: "israel",
    capital: "jerusalem",
    currency: "shekel",
    native_language: ["hebrew", "arabic"],
    famous_for: "jewish-majority, aliyah, al aqsa mosque, jerusalem",
    phone_code: "+972",
    flag: "https://flagpedia.net/data/flags/h80/il.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 20770,
      mi2: 8020,
    },
    continent: "as",
    iso: {
      numeric: "376",
      alpha_2: "il",
      alpha_3: "isr",
    },
    tld: ".il",
    constitutional_form: "republic",
    language_codes: ["ar-IL", "he-IL"],
    is_landlocked: false,
  },
  {
    country: "italy",
    capital: "rome",
    currency: "euro",
    native_language: ["italian"],
    famous_for: "ferrari, spaghetti, pizza, fashion, venice",
    phone_code: "+39",
    flag: "https://flagpedia.net/data/flags/h80/it.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 301339,
      mi2: 116348,
    },
    continent: "eu",
    iso: {
      numeric: "380",
      alpha_2: "it",
      alpha_3: "ita",
    },
    tld: ".it",
    constitutional_form: "republic",
    language_codes: ["it-IT"],
    is_landlocked: false,
  },
  {
    country: "jamaica",
    capital: "kingston",
    currency: "jamaican dollar",
    native_language: ["english"],
    famous_for: "blue mountain coffee",
    phone_code: "+1-876",
    flag: "https://flagpedia.net/data/flags/h80/jm.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 10991,
      mi2: 4244,
    },
    continent: "na",
    iso: {
      numeric: "388",
      alpha_2: "jm",
      alpha_3: "jam",
    },
    tld: ".jm",
    constitutional_form: "constitutional monarchy",
    language_codes: ["en-JM"],
    is_landlocked: false,
  },
  {
    country: "japan",
    capital: "tokyo",
    currency: "yen",
    native_language: ["japanese"],
    famous_for:
      "politeness, anime, sushi, samurai, nintendo karate, cars and robotics",
    phone_code: "+81",
    flag: "https://flagpedia.net/data/flags/h80/jp.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 377975,
      mi2: 145937,
    },
    continent: "as",
    iso: {
      numeric: "392",
      alpha_2: "jp",
      alpha_3: "jpn",
    },
    tld: ".jp",
    constitutional_form: "constitutional monarchy",
    language_codes: ["ja-JP"],
    is_landlocked: false,
  },
  {
    country: "jordan",
    capital: "amman",
    currency: "jordanian dinar",
    native_language: ["arabic"],
    famous_for: "petra",
    phone_code: "+962",
    flag: "https://flagpedia.net/data/flags/h80/jo.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 89342,
      mi2: 34495,
    },
    continent: "as",
    iso: {
      numeric: "400",
      alpha_2: "jo",
      alpha_3: "jor",
    },
    tld: ".jo",
    constitutional_form: "constitutional monarchy",
    language_codes: ["ar-JO"],
    is_landlocked: false,
  },

  {
    country: "kenya",
    capital: "nairobi",
    currency: "kenyan shilling",
    native_language: ["swahili", "english"],
    famous_for: "masai people, safari tourism",
    phone_code: "+254",
    flag: "https://flagpedia.net/data/flags/h80/ke.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 580367,
      mi2: 224081,
    },
    continent: "af",
    iso: {
      numeric: "404",
      alpha_2: "ke",
      alpha_3: "ken",
    },
    tld: ".ke",
    constitutional_form: "republic",
    language_codes: ["en-KE", "sw-KE"],
    is_landlocked: false,
  },

  {
    country: "north korea",
    capital: "pyongyang",
    currency: "north korean won",
    native_language: ["korean"],
    famous_for: "communism, kim jeong 2, nuclear weapon",
    phone_code: "+850",
    flag: "https://flagpedia.net/data/flags/h80/kp.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 120540,
      mi2: 46540,
    },
    continent: "as",
    iso: {
      numeric: "408",
      alpha_2: "kp",
      alpha_3: "prk",
    },
    tld: ".kp",
    constitutional_form: "republic",
    language_codes: ["ko-KP"],
    is_landlocked: false,
  },
  {
    country: "south korea",
    capital: "seoul",
    currency: "south korean won",
    native_language: ["korean"],
    famous_for: "k-pop, samsung, hyundai, kia and kim chi",
    phone_code: "+82",
    flag: "https://flagpedia.net/data/flags/h80/kr.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 100210,
      mi2: 38690,
    },
    continent: "as",
    iso: {
      numeric: "410",
      alpha_2: "kr",
      alpha_3: "kor",
    },
    tld: ".kr",
    constitutional_form: "republic",
    language_codes: ["ko-KR"],
    is_landlocked: false,
  },
  {
    country: "kosovo",
    capital: "pristina",
    currency: "euro",
    native_language: ["albanian", "serbian"],
    famous_for: "mountains and wine",
    phone_code: "+383",
    flag: "https://flagpedia.net/data/flags/h80/xk.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 10887,
      mi2: 4203,
    },
    continent: "eu",
    iso: {
      numeric: "383",
      alpha_2: "xk",
      alpha_3: "xkx",
    },
    tld: ".rs",
    constitutional_form: "republic",
    language_codes: ["sr-XK", "sq-XK"],
    is_landlocked: true,
  },

  {
    country: "latvia",
    capital: "riga",
    currency: "lats",
    native_language: ["latvian"],
    famous_for: "old town, home to widest waterfall in europe",
    phone_code: "+371",
    flag: "https://flagpedia.net/data/flags/h80/lv.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 64559,
      mi2: 24926,
    },
    continent: "eu",
    iso: {
      numeric: "428",
      alpha_2: "lv",
      alpha_3: "lva",
    },
    tld: ".lv",
    constitutional_form: "republic",
    language_codes: ["lv-LV"],
    is_landlocked: false,
  },
  {
    country: "libya",
    capital: "tripoli",
    currency: "libyan dinar",
    native_language: ["arabic"],
    famous_for: "sahara desert",
    phone_code: "+218",
    flag: "https://flagpedia.net/data/flags/h80/ly.png",
    drive_direction: "right",
    alcohol_prohibition: "nationwide",
    area: {
      km2: 1759540,
      mi2: 679360,
    },
    continent: "af",
    iso: {
      numeric: "434",
      alpha_2: "ly",
      alpha_3: "lby",
    },
    tld: ".ly",
    constitutional_form: "n/a",
    language_codes: ["ar-LY"],
    is_landlocked: false,
  },
  {
    country: "liechtenstein",
    capital: "vaduz",
    currency: "swiss franc",
    native_language: ["german"],
    famous_for:
      "unbelievable transformation from rural to wealthiest population within 60 years",
    phone_code: "+423",
    flag: "https://flagpedia.net/data/flags/h80/li.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 160,
      mi2: 62,
    },
    continent: "eu",
    iso: {
      numeric: "438",
      alpha_2: "li",
      alpha_3: "lie",
    },
    tld: ".li",
    constitutional_form: "constitutional monarchy",
    language_codes: ["de-LI"],
    is_landlocked: true,
  },

  {
    country: "luxembourg",
    capital: "luxembourg",
    currency: "euro",
    native_language: ["german", "french", "luxembourgish"],
    famous_for:
      "europe's most powerful investment management centre and steel manufacturing",
    phone_code: "+352",
    flag: "https://flagpedia.net/data/flags/h80/lu.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 2586,
      mi2: 998,
    },
    continent: "eu",
    iso: {
      numeric: "442",
      alpha_2: "lu",
      alpha_3: "lux",
    },
    tld: ".lu",
    constitutional_form: "constitutional monarchy",
    language_codes: ["de-LU", "fr-LU", "lb-LU"],
    is_landlocked: true,
  },
  {
    country: "north macedonia",
    capital: "skopje",
    currency: "macedonian denar",
    native_language: ["macedonian"],
    famous_for: "great empire's history",
    phone_code: "+389",
    flag: "https://flagpedia.net/data/flags/h80/mk.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 25713,
      mi2: 9928,
    },
    continent: "eu",
    iso: {
      numeric: "807",
      alpha_2: "mk",
      alpha_3: "mkd",
    },
    tld: ".mk",
    constitutional_form: "republic",
    language_codes: ["mk-MK", "sq-MK"],
    is_landlocked: true,
  },

  {
    country: "malta",
    capital: "valletta",
    currency: "euro",
    native_language: ["maltese", "english"],
    famous_for: "warm climate, architectural and historical monuments",
    phone_code: "+356",
    flag: "https://flagpedia.net/data/flags/h80/mt.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 316,
      mi2: 122,
    },
    continent: "eu",
    iso: {
      numeric: "470",
      alpha_2: "mt",
      alpha_3: "mlt",
    },
    tld: ".mt",
    constitutional_form: "republic",
    language_codes: ["en-MT", "mt-MT"],
    is_landlocked: false,
  },

  {
    country: "mexico",
    capital: "mexico city",
    currency: "mexican peso",
    native_language: ["spanish"],
    famous_for: "sombero hat, taco, aztec, salsa",
    phone_code: "+52",
    flag: "https://flagpedia.net/data/flags/h80/mx.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 1964375,
      mi2: 758449,
    },
    continent: "na",
    iso: {
      numeric: "484",
      alpha_2: "mx",
      alpha_3: "mex",
    },
    tld: ".mx",
    constitutional_form: "republic",
    language_codes: ["es-MX"],
    is_landlocked: false,
  },

  {
    country: "moldova",
    capital: "chisinau",
    currency: "moldovan leu",
    native_language: ["moldovan (romanian)"],
    famous_for: "wine",
    phone_code: "+373",
    flag: "https://flagpedia.net/data/flags/h80/md.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 33846,
      mi2: 13068,
    },
    continent: "eu",
    iso: {
      numeric: "498",
      alpha_2: "md",
      alpha_3: "mda",
    },
    tld: ".md",
    constitutional_form: "republic",
    language_codes: ["ro-MD"],
    is_landlocked: true,
  },

  {
    country: "montenegro",
    capital: "podgorica",
    currency: "euro",
    native_language: ["montenegrin"],
    famous_for: "montenegrin coast",
    phone_code: "+377",
    flag: "https://flagpedia.net/data/flags/h80/me.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 13812,
      mi2: 5333,
    },
    continent: "eu",
    iso: {
      numeric: "499",
      alpha_2: "me",
      alpha_3: "mne",
    },
    tld: ".me",
    constitutional_form: "republic",
    language_codes: ["sr-ME"],
    is_landlocked: false,
  },
  {
    country: "morocco",
    capital: "rabat",
    currency: "moroccan dirham",
    native_language: ["arabic"],
    famous_for: "medinas, beautiful handcrafts and traditional products",
    phone_code: "+212",
    flag: "https://flagpedia.net/data/flags/h80/ma.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 446550,
      mi2: 172410,
    },
    continent: "af",
    iso: {
      numeric: "504",
      alpha_2: "ma",
      alpha_3: "mar",
    },
    tld: ".ma",
    constitutional_form: "constitutional monarchy",
    language_codes: ["ar-MA"],
    is_landlocked: false,
  },
  {
    country: "netherlands",
    capital: "amsterdam",
    currency: "euro",
    native_language: ["dutch"],
    famous_for: "legal drugs, tulip flowers and windmills",
    phone_code: "+31",
    flag: "https://flagpedia.net/data/flags/h80/nl.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 41850,
      mi2: 16160,
    },
    continent: "eu",
    iso: {
      numeric: "528",
      alpha_2: "nl",
      alpha_3: "nld",
    },
    tld: ".nl",
    constitutional_form: "constitutional monarchy",
    language_codes: ["nl-NL"],
    is_landlocked: false,
  },
  {
    country: "new zealand",
    capital: "wellington",
    currency: "new zealand dollar",
    native_language: ["english"],
    famous_for: "national rugby team",
    phone_code: "+64",
    flag: "https://flagpedia.net/data/flags/h80/nz.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 270467,
      mi2: 104428,
    },
    continent: "oc",
    iso: {
      numeric: "554",
      alpha_2: "nz",
      alpha_3: "nzl",
    },
    tld: ".nz",
    constitutional_form: "constitutional monarchy",
    language_codes: ["en-NZ"],
    is_landlocked: false,
  },

  {
    country: "nigeria",
    capital: "abuja",
    currency: "naira",
    native_language: ["english"],
    famous_for: "most common sub saharan tourists, petroleum production",
    phone_code: "+234",
    flag: "https://flagpedia.net/data/flags/h80/ng.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 923768,
      mi2: 356669,
    },
    continent: "af",
    iso: {
      numeric: "566",
      alpha_2: "ng",
      alpha_3: "nga",
    },
    tld: ".ng",
    constitutional_form: "republic",
    language_codes: ["en-NG"],
    is_landlocked: false,
  },
  {
    country: "norway",
    capital: "oslo",
    currency: "norwegian krone",
    native_language: ["norwegian"],
    famous_for: "oil, fjords, mountains and midnight sun",
    phone_code: "+47",
    flag: "https://flagpedia.net/data/flags/h80/no.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 385207,
      mi2: 148729,
    },
    continent: "eu",
    iso: {
      numeric: "578",
      alpha_2: "no",
      alpha_3: "nor",
    },
    tld: ".no",
    constitutional_form: "constitutional monarchy",
    language_codes: ["no-NO"],
    is_landlocked: false,
  },

  {
    country: "pakistan",
    capital: "islamabad",
    currency: "pakistani rupee",
    native_language: ["urdu", "english"],
    famous_for: "producing footballs, cricket team",
    phone_code: "+92",
    flag: "https://flagpedia.net/data/flags/h80/pk.png",
    drive_direction: "left",
    alcohol_prohibition: "limited",
    area: {
      km2: 907843,
      mi2: 350520,
    },
    continent: "as",
    iso: {
      numeric: "586",
      alpha_2: "pk",
      alpha_3: "pak",
    },
    tld: ".pk",
    constitutional_form: "republic",
    language_codes: ["en-PK", "ur-PK"],
    is_landlocked: false,
  },

  {
    country: "panama",
    capital: "panama city",
    currency: "balboa",
    native_language: ["spanish"],
    famous_for: "panama canal, birding, snorkeling and rafting",
    phone_code: "+507",
    flag: "https://flagpedia.net/data/flags/h80/pa.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 75417,
      mi2: 29119,
    },
    continent: "na",
    iso: {
      numeric: "591",
      alpha_2: "pa",
      alpha_3: "pan",
    },
    tld: ".pa",
    constitutional_form: "republic",
    language_codes: ["es-PA"],
    is_landlocked: false,
  },

  {
    country: "paraguay",
    capital: "asuncion",
    currency: "guarani",
    native_language: ["spanish", "guarani"],
    famous_for: "largest naval power",
    phone_code: "+595",
    flag: "https://flagpedia.net/data/flags/h80/py.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 406752,
      mi2: 157048,
    },
    continent: "sa",
    iso: {
      numeric: "600",
      alpha_2: "py",
      alpha_3: "pry",
    },
    tld: ".py",
    constitutional_form: "republic",
    language_codes: ["es-PY", "gn-PY"],
    is_landlocked: true,
  },
  {
    country: "peru",
    capital: "lima",
    currency: "nuevo sol",
    native_language: ["spanish"],
    famous_for: "machu picchu",
    phone_code: "+51",
    flag: "https://flagpedia.net/data/flags/h80/pe.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 1285216,
      mi2: 496225,
    },
    continent: "sa",
    iso: {
      numeric: "604",
      alpha_2: "pe",
      alpha_3: "per",
    },
    tld: ".pe",
    constitutional_form: "republic",
    language_codes: ["es-PE", "qu-PE"],
    is_landlocked: false,
  },
  {
    country: "philippines",
    capital: "manila",
    currency: "philippine peso",
    native_language: ["filipino", "english"],
    famous_for: "domestic workers, ferdinand marcos, manny pacquiao",
    phone_code: "+63",
    flag: "https://flagpedia.net/data/flags/h80/ph.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 300000,
      mi2: 120000,
    },
    continent: "as",
    iso: {
      numeric: "608",
      alpha_2: "ph",
      alpha_3: "phl",
    },
    tld: ".ph",
    constitutional_form: "republic",
    language_codes: ["en-PH", "tl-PH"],
    is_landlocked: false,
  },
  {
    country: "poland",
    capital: "warsaw",
    currency: "zloty",
    native_language: ["polish"],
    famous_for: "pierogi and potatoes",
    phone_code: "+48",
    flag: "https://flagpedia.net/data/flags/h80/pl.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 312696,
      mi2: 120733,
    },
    continent: "eu",
    iso: {
      numeric: "616",
      alpha_2: "pl",
      alpha_3: "pol",
    },
    tld: ".pl",
    constitutional_form: "republic",
    language_codes: ["pl-PL"],
    is_landlocked: false,
  },
  {
    country: "portugal",
    capital: "lisbon",
    currency: "euro",
    native_language: ["portuguese"],
    famous_for: "beaches, food and cristiano ronaldo",
    phone_code: "+351",
    flag: "https://flagpedia.net/data/flags/h80/pt.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 92090,
      mi2: 35560,
    },
    continent: "eu",
    iso: {
      numeric: "620",
      alpha_2: "pt",
      alpha_3: "prt",
    },
    tld: ".pt",
    constitutional_form: "republic",
    language_codes: ["pt-PT"],
    is_landlocked: false,
  },
  {
    country: "qatar",
    capital: "doha",
    currency: "qatari riyal",
    native_language: ["arabic"],
    famous_for: "qatar airlines",
    phone_code: "+974",
    flag: "https://flagpedia.net/data/flags/h80/qa.png",
    drive_direction: "right",
    alcohol_prohibition: "limited",
    area: {
      km2: 11586,
      mi2: 4473,
    },
    continent: "as",
    iso: {
      numeric: "634",
      alpha_2: "qa",
      alpha_3: "qat",
    },
    tld: ".qa",
    constitutional_form: "absolute monarchy",
    language_codes: ["ar-QA"],
    is_landlocked: false,
  },
  {
    country: "romania",
    capital: "bucharest",
    currency: "romanian rupee",
    native_language: ["romanian"],
    famous_for: "dracula",
    phone_code: "+40",
    flag: "https://flagpedia.net/data/flags/h80/ro.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 238397,
      mi2: 92046,
    },
    continent: "eu",
    iso: {
      numeric: "642",
      alpha_2: "ro",
      alpha_3: "rou",
    },
    tld: ".ro",
    constitutional_form: "republic",
    language_codes: ["ro-RO"],
    is_landlocked: false,
  },
  {
    country: "russia",
    capital: "moscow",
    currency: "ruble",
    native_language: ["russian"],
    famous_for: "vodka, military, matroyshka dolls and cold climate",
    phone_code: "+7",
    flag: "https://flagpedia.net/data/flags/h80/ru.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 17098246,
      mi2: 6601670,
    },
    continent: "eu/as",
    iso: {
      numeric: "643",
      alpha_2: "ru",
      alpha_3: "rus",
    },
    tld: ".ru",
    constitutional_form: "republic",
    language_codes: ["ru-RU"],
    is_landlocked: false,
  },

  {
    country: "saudi arabia",
    capital: "riyadh",
    currency: "saudi riyal",
    native_language: ["arabic"],
    famous_for: "strict rules, wahhabism, mecca and madina",
    phone_code: "+966",
    flag: "https://flagpedia.net/data/flags/h80/sa.png",
    drive_direction: "right",
    alcohol_prohibition: "nationwide",
    area: {
      km2: 2149690,
      mi2: 830000,
    },
    continent: "as",
    iso: {
      numeric: "682",
      alpha_2: "sa",
      alpha_3: "sau",
    },
    tld: ".sa",
    constitutional_form: "absolute monarchy",
    language_codes: ["ar-SA"],
    is_landlocked: false,
  },
  {
    country: "senegal",
    capital: "dakar",
    currency: "west african cfa franc",
    native_language: ["french"],
    famous_for: "traditional wrestling, football and exotic dance",
    phone_code: "+221",
    flag: "https://flagpedia.net/data/flags/h80/sn.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 196722,
      mi2: 75955,
    },
    continent: "af",
    iso: {
      numeric: "686",
      alpha_2: "sn",
      alpha_3: "sen",
    },
    tld: ".sn",
    constitutional_form: "republic",
    language_codes: ["fr-SN"],
    is_landlocked: false,
  },
  {
    country: "serbia",
    capital: "belgrade",
    currency: "serbian dinar",
    native_language: ["serbian"],
    famous_for: "culture, history, delicious cuisine, and nightlife",
    phone_code: "+381",
    flag: "https://flagpedia.net/data/flags/h80/rs.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 88361,
      mi2: 34116,
    },
    continent: "eu",
    iso: {
      numeric: "688",
      alpha_2: "rs",
      alpha_3: "srb",
    },
    tld: ".rs",
    constitutional_form: "republic",
    language_codes: ["sr-RS"],
    is_landlocked: true,
  },

  {
    country: "singapore",
    capital: "singapore",
    currency: "singapore dollar",
    native_language: ["english", "malay", "mandarin chinese"],
    famous_for: "cleanliness, marina bay and strict laws",
    phone_code: "+65",
    flag: "https://flagpedia.net/data/flags/h80/sg.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 726,
      mi2: 280,
    },
    continent: "as",
    iso: {
      numeric: "702",
      alpha_2: "sg",
      alpha_3: "sgp",
    },
    tld: ".sg",
    constitutional_form: "republic",
    language_codes: ["en-SG", "ms-SG", "zh-SG"],
    is_landlocked: false,
  },
  {
    country: "slovakia",
    capital: "bratislava",
    currency: "euro",
    native_language: ["slovak"],
    famous_for: "eset and sygic",
    phone_code: "+421",
    flag: "https://flagpedia.net/data/flags/h80/sk.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 49037,
      mi2: 18933,
    },
    continent: "eu",
    iso: {
      numeric: "703",
      alpha_2: "sk",
      alpha_3: "svk",
    },
    tld: ".sk",
    constitutional_form: "republic",
    language_codes: ["sk-SK"],
    is_landlocked: true,
  },
  {
    country: "slovenia",
    capital: "ljubljana",
    currency: "euro",
    native_language: ["slovene"],
    famous_for: "caves",
    phone_code: "+386",
    flag: "https://flagpedia.net/data/flags/h80/si.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 20273,
      mi2: 7827,
    },
    continent: "eu",
    iso: {
      numeric: "705",
      alpha_2: "si",
      alpha_3: "svn",
    },
    tld: ".si",
    constitutional_form: "republic",
    language_codes: ["sl-SI"],
    is_landlocked: false,
  },

  {
    country: "south africa",
    capital: "pretoria, cape town,bloemfontein",
    currency: "rand",
    native_language: ["zulu", "xhosa", "afrikaans"],
    famous_for: "nelson mandela and safari",
    phone_code: "+27",
    flag: "https://flagpedia.net/data/flags/h80/za.png",
    drive_direction: "left",
    alcohol_prohibition: "limited",
    area: {
      km2: 1221037,
      mi2: 471445,
    },
    continent: "af",
    iso: {
      numeric: "710",
      alpha_2: "za",
      alpha_3: "zaf",
    },
    tld: ".za",
    constitutional_form: "republic",
    language_codes: ["af-ZA", "en-ZA", "xh-ZA", "zu-ZA"],
    is_landlocked: false,
  },

  {
    country: "spain",
    capital: "madrid",
    currency: "euro",
    native_language: ["spanish", "catalan"],
    famous_for: "salsa and bullfight",
    phone_code: "+34",
    flag: "https://flagpedia.net/data/flags/h80/es.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 505992,
      mi2: 195365,
    },
    continent: "eu",
    iso: {
      numeric: "724",
      alpha_2: "es",
      alpha_3: "esp",
    },
    tld: ".es",
    constitutional_form: "constitutional monarchy",
    language_codes: ["ca-ES", "es-ES"],
    is_landlocked: false,
  },
  {
    country: "sri lanka",
    capital: "colombo",
    currency: "sri lankan rupee",
    native_language: ["sinhala", "tamil"],
    famous_for: "ceylon tea",
    phone_code: "+94",
    flag: "https://flagpedia.net/data/flags/h80/lk.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 65610,
      mi2: 25330,
    },
    continent: "as",
    iso: {
      numeric: "144",
      alpha_2: "lk",
      alpha_3: "lka",
    },
    tld: ".lk",
    constitutional_form: "republic",
    language_codes: ["si-LK", "ta-LK"],
    is_landlocked: false,
  },

  {
    country: "sweden",
    capital: "stockholm",
    currency: "swedish krona",
    native_language: ["swedish"],
    famous_for: "ikea, meatballs, volvo",
    phone_code: "+46",
    flag: "https://flagpedia.net/data/flags/h80/se.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 450295,
      mi2: 173860,
    },
    continent: "eu",
    iso: {
      numeric: "752",
      alpha_2: "se",
      alpha_3: "swe",
    },
    tld: ".se",
    constitutional_form: "constitutional monarchy",
    language_codes: ["sv-SE"],
    is_landlocked: false,
  },
  {
    country: "switzerland",
    capital: "berne",
    currency: "swiss franc",
    native_language: ["german", "french", "italian", "romansh"],
    famous_for: "alps, natural beauty, chocolates and watches",
    flag: "https://flagpedia.net/data/flags/h80/ch.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 41284,
      mi2: 15940,
    },
    continent: "eu",
    iso: {
      numeric: "756",
      alpha_2: "ch",
      alpha_3: "che",
    },
    tld: ".ch",
    constitutional_form: "republic",
    language_codes: ["de-CH", "fr-CH", "it-CH", "rm-CH"],
    is_landlocked: true,
  },

  {
    country: "thailand",
    capital: "bangkok",
    currency: "thai baht",
    native_language: ["thai"],
    famous_for: "massages, shopping and buddhists",
    phone_code: "+66",
    flag: "https://flagpedia.net/data/flags/h80/th.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 513120,
      mi2: 198120,
    },
    continent: "as",
    iso: {
      numeric: "764",
      alpha_2: "th",
      alpha_3: "tha",
    },
    tld: ".th",
    constitutional_form: "constitutional monarchy",
    language_codes: ["th-TH"],
    is_landlocked: false,
  },

  {
    country: "tunisia",
    capital: "tunis",
    currency: "tunisian dinar",
    native_language: ["tunisian", "french"],
    famous_for: "gold beaches, sunny weather and affordable luxuries",
    phone_code: "+216",
    flag: "https://flagpedia.net/data/flags/h80/tn.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 163610,
      mi2: 63170,
    },
    continent: "af",
    iso: {
      numeric: "788",
      alpha_2: "tn",
      alpha_3: "tun",
    },
    tld: ".tn",
    constitutional_form: "republic",
    language_codes: ["ar-TN", "fr-TN"],
    is_landlocked: false,
  },
  {
    country: "turkey",
    capital: "ankara",
    currency: "turkish lira",
    native_language: ["turkish"],
    famous_for: "big mountain ranges, istanbul, shawarma",
    phone_code: "+90",
    flag: "https://flagpedia.net/data/flags/h80/tr.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 783562,
      mi2: 302535,
    },
    continent: "eu/as",
    iso: {
      numeric: "792",
      alpha_2: "tr",
      alpha_3: "tur",
    },
    tld: ".tr",
    constitutional_form: "republic",
    language_codes: ["tr-TR"],
    is_landlocked: false,
  },

  {
    country: "ukraine",
    capital: "kiev",
    currency: "hryvnia",
    native_language: ["ukrainian", "russian"],
    famous_for: "agricultural production",
    phone_code: "+380",
    flag: "https://flagpedia.net/data/flags/h80/ua.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 603500,
      mi2: 233000,
    },
    continent: "eu",
    iso: {
      numeric: "804",
      alpha_2: "ua",
      alpha_3: "ukr",
    },
    tld: ".ua",
    constitutional_form: "republic",
    language_codes: ["ru-UA", "uk-UA"],
    is_landlocked: false,
  },
  {
    country: "united arab emirates",
    capital: "abu dhabi",
    currency: "dirham",
    native_language: ["arabic"],
    famous_for: "dubai, rich seikhs, burj al arab",
    phone_code: "+971",
    flag: "https://flagpedia.net/data/flags/h80/ae.png",
    drive_direction: "right",
    alcohol_prohibition: "limited",
    area: {
      km2: 83600,
      mi2: 32300,
    },
    continent: "as",
    iso: {
      numeric: "784",
      alpha_2: "ae",
      alpha_3: "are",
    },
    tld: ".ae",
    constitutional_form: "constitutional monarchy",
    language_codes: ["ar-AE"],
    is_landlocked: false,
  },
  {
    country: "united kingdom",
    capital: "london",
    currency: "pound sterling",
    native_language: ["english"],
    famous_for:
      "david beckham, fish and chips, big ben, red buses, black cabs, oasis, blur, the beatles, london and tea",
    phone_code: "+44",
    flag: "https://flagpedia.net/data/flags/h80/gb.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 242495,
      mi2: 93628,
    },
    continent: "eu",
    iso: {
      numeric: "826",
      alpha_2: "gb",
      alpha_3: "gbr",
    },
    tld: ".gb/.uk",
    constitutional_form: "constitutional monarchy",
    language_codes: ["en-GB"],
    is_landlocked: false,
  },
  {
    country: "united states of america",
    capital: "washington d.c.",
    currency: "united states dollar",
    native_language: ["english", "spanish"],
    famous_for: "grand canyon and mount rushmore",
    phone_code: "+1",
    flag: "https://flagpedia.net/data/flags/h80/us.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 9833517,
      mi2: 3796742,
    },
    continent: "na",
    iso: {
      numeric: "840",
      alpha_2: "us",
      alpha_3: "usa",
    },
    tld: ".us",
    constitutional_form: "republic",
    language_codes: ["en-US", "es-US"],
    is_landlocked: false,
  },
  {
    country: "uruguay",
    capital: "montevideo",
    currency: "uruguayan peso",
    native_language: ["spanish"],
    famous_for: "wine producers",
    phone_code: "+589",
    flag: "https://flagpedia.net/data/flags/h80/uy.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 176215,
      mi2: 68037,
    },
    continent: "sa",
    iso: {
      numeric: "858",
      alpha_2: "uy",
      alpha_3: "ury",
    },
    tld: ".uy",
    constitutional_form: "republic",
    language_codes: ["sp-UY"],
    is_landlocked: false,
  },
  {
    country: "uzbekistan",
    capital: "tashkent",
    currency: "uzbekistan som",
    native_language: ["uzbek", "russian"],
    famous_for: "mosques and mausoleums",
    phone_code: "+998",
    flag: "https://flagpedia.net/data/flags/h80/uz.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 447400,
      mi2: 172700,
    },
    continent: "as",
    iso: {
      numeric: "860",
      alpha_2: "uz",
      alpha_3: "uzb",
    },
    tld: ".uz",
    constitutional_form: "republic",
    language_codes: ["ru-UZ", "uz-UZ"],
    is_landlocked: true,
  },

  {
    country: "venezuela",
    capital: "caracas",
    currency: "bolivar fuerte",
    native_language: ["spanish"],
    famous_for: "petroleum industry",
    phone_code: "+58",
    flag: "https://flagpedia.net/data/flags/h80/ve.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 916445,
      mi2: 353841,
    },
    continent: "sa",
    iso: {
      numeric: "862",
      alpha_2: "ve",
      alpha_3: "ven",
    },
    tld: ".ve",
    constitutional_form: "republic",
    language_codes: ["es-VE"],
    is_landlocked: false,
  },
  {
    country: "vietnam",
    capital: "hanoi",
    currency: "dong",
    native_language: ["vietnamese"],
    famous_for: "rice exporter",
    phone_code: "+84",
    flag: "https://flagpedia.net/data/flags/h80/vn.png",
    drive_direction: "right",
    alcohol_prohibition: "none",
    area: {
      km2: 331212,
      mi2: 127882,
    },
    continent: "as",
    iso: {
      numeric: "704",
      alpha_2: "vn",
      alpha_3: "vnm",
    },
    tld: ".vn",
    constitutional_form: "republic",
    language_codes: ["vi-VN"],
    is_landlocked: false,
  },
  {
    country: "yemen",
    capital: "sanaa",
    currency: "yemeni rial",
    native_language: ["arabic"],
    famous_for: "home to world's oldest skyscraper city",
    phone_code: "+967",
    flag: "https://flagpedia.net/data/flags/h80/ye.png",
    drive_direction: "right",
    alcohol_prohibition: "regional",
    area: {
      km2: 527968,
      mi2: 203850,
    },
    continent: "as",
    iso: {
      numeric: "887",
      alpha_2: "ye",
      alpha_3: "yem",
    },
    tld: ".ye",
    constitutional_form: "n/a",
    language_codes: ["ar-YE"],
    is_landlocked: false,
  },
  {
    country: "zimbabwe",
    capital: "harare",
    currency: "united states dollar",
    native_language: ["english"],
    famous_for: "hwange and mana pools teem with wildlife",
    phone_code: "+263",
    flag: "https://flagpedia.net/data/flags/h80/zw.png",
    drive_direction: "left",
    alcohol_prohibition: "none",
    area: {
      km2: 390757,
      mi2: 150872,
    },
    continent: "af",
    iso: {
      numeric: "716",
      alpha_2: "zw",
      alpha_3: "zwe",
    },
    tld: ".zw",
    constitutional_form: "republic",
    language_codes: ["en-ZW"],
    is_landlocked: true,
  },
];
